[package]
name = "test_coprocessor"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tikv_util = { path = "../tikv_util" }
tikv = { path = "../../", default-features = false }
tipb = { git = "https://github.com/pingcap/tipb.git" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", rev = "3989027cb1ea74a513205d84adbce69d7e46b97d" }
protobuf = "~2.0"
test_storage = { path = "../test_storage" }
futures = "0.1"
